#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum WINMODE { MODE_FULL, MODE_WIN };

	enum COMPONENTID { ID_DYNAMIC, ID_STATIC, ID_END };

	enum INFO {	INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };

	enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };

	enum TEXTUREID { TEX_NORMAL, TEX_CUBE, TEX_END };

	enum RENDERID { RENDER_PRIORITY, RENDER_NONALPHA, RENDER_ALPHATEST, RENDER_ALPHA, RENDER_UI, RENDER_DEBUG_COLLIDER, RENDER_END };

	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };

	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum CAMERAID { CAMERA_FPV_PERSPECTIVE, CAMERA_TPV_PERSPECTIVE, CAMERA_FREE_PERSPECTIVE, CAMERA_WORKING, CAMERA_END };

	enum MESHRENDERMODE { MESH_SOLID, MESH_WIREFRAME, MESH_NONE, MESH_MODE_END };

	enum EYE_MOVE { EYE_STATIC, EYE_LINEAR, EYE_TRACE };

	enum AT_MOVE { AT_STATIC, AT_POINT, AT_POINT_LINEAR, AT_TRACE };

	enum EYE_PARAM
	{
		EYE_POS = 0,
		EYE_FROM = 0,
		EYE_TRACE_RELATIVE = 0,
		EYE_TO = 1,
		EYE_PARAM_END
	};

	enum AT_PARAM
	{
		AT_DIRECTION = 0,
		AT_POS = 0,
		AT_FROM = 0,
		AT_TRACE_RELATIVE = 0,
		AT_TO = 1,
		AT_PARAM_END
	};

}
#endif // Engine_Enum_h__
