#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum WINMODE { MODE_FULL, MODE_WIN };

	enum COMPONENTID { ID_DYNAMIC, ID_STATIC, ID_END };

	enum INFO {	INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };

	enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };

	enum TEXTUREID { TEX_NORMAL, TEX_CUBE, TEX_END };

	enum RENDERID { RENDER_PRIORITY, RENDER_NONALPHA, RENDER_ALPHA, RENDER_UI, RENDER_DEBUG_COLLIDER, RENDER_END };

	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };

	enum MOUSEMOVESTATE {	DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum CAMERAID { CAMERA_FPV_PERSPECTIVE, CAMERA_TPV_PERSPECTIVE, CAMERA_END };

	enum VTXSTRUCTTYPE { VTXSTRUCT_DEFAULT, VTXSTRUCT_COL, VTXSTRUCT_TEX, VTXSTRUCT_CUBE, VTXSTRUCT_END }; // Vertex 메모리 버퍼의 구조체 타입

	enum MESHRENDERMODE { MESH_SOLID, MESH_WIREFRAME, MESH_NONE, MESH_MODE_END };

}
#endif // Engine_Enum_h__
