#pragma once

/* 벽 방향 */
enum class EWallDir
{
	NONE,
	EAST,
	SOUTH,
	WEST,
	NORTH,

	MAX,
};

enum JUMPSTATE { JUMP_NOT, JUMP_PARABOLIC, JUMP_FREEFALL, JUMP_END };

enum BULLETID { BULLET_DEFAULT, BULLET_SMALL, BULLET_END };

enum COLLISIONID
{
	COLL_PLAYER,	// COLL_ID1,
	COLL_MONSTER,	// COLL_ID2,
	COLL_PBULLET,	// COLL_ID3,
	COLL_MBULLET,	// COLL_ID4,
	COLL_WALL,		// COLL_ID5,
	COLL_ITEM,		// COLL_ID6,
	COLL_OBSTACLE,	// COLL_ID7,
	COLL_EXPLODERANGE,// COLL_ID8,
	COLL_BUTTON,	// COLL_ID9,
	COLL_ID10,		// COLL_ID10,
	COLL_ID11,		// COLL_ID11,
	COLL_ID12,		// COLL_ID12,
	COLL_ID13,		// COLL_ID13,
	COLL_ID14,		// COLL_ID14,
	COLL_ID15,		// COLL_ID15,
	COLL_ID16,		// COLL_ID16,
	COLL_ID17,		// COLL_ID17,
	COLL_ID18,		// COLL_ID18,
	COLL_ID19,		// COLL_ID19,
	COLL_ID20,		// COLL_ID20,
	COLL_ID21,		// COLL_ID21,
	COLL_ID22,		// COLL_ID22,
	COLL_ID23,		// COLL_ID23,
	COLL_ID24,		// COLL_ID24,
	COLL_ID25,		// COLL_ID25,
	COLL_ID26,		// COLL_ID26,
	COLL_ID27,		// COLL_ID27,
	COLL_ID28,		// COLL_ID28,
	COLL_ID29,		// COLL_ID29,
	COLL_ID30,		// COLL_ID30,
	COLL_ID31,		// COLL_ID31,
	COLL_ID32,		// COLL_ID32,

	COLL_MAX
};

/* 맵 배치 오브젝트 타입 */
enum class EObjectType
{
	NONE = 0,

	BREAKABLE_FRUSTUM = 1,
	UNBREAKABLE_FRUSTUM,
	EXPLOSIVE_FRUSTUM,

	Skull = 11,
	Boss1,
	Speyeder,
	Magmamouth,
	Worm,

	ITEM_NONE = 31,
	ITEM_HEART,
	ITEM_GEM,
	ITEM_ENERGY,
	ITEM_MAX,

	MAX,
};

enum class ERoomEventType
{
	NONE,

	ROOM_CHANGED,
	ROOM_BEGIN,
	ROOM_CLEAR,
	
	BUTTON,

	MAX,
};

enum ITEMID { ITEM_HEAL, ITEM_SKILLGAUGE, ITEM_END };

enum class EContaminateType
{
	NONE,

	LAVA,

	MAX,
};

enum class ETileType
{
	NONE,

	SPRITE,
	BUTTON,

	MAX,
};